name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install knitr
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends r-cran-knitr texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-bibtex-extra
        /usr/lib/R/site-library/knitr/bin/knit moving-target-evostar-2019.Rnw -o paper.pdf
