name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install knitr
      run: |
        sudo apt-get update
        sudo apt-get install -y r-cran-knitr
        /usr/lib/R/site-library/knitr/bin/knit moving-target-evostar-2019.Rnw -o paper.pdf
